---
# transfer_funds
# wait_for_funds
# initialize_sp ${SECTOR_SIZE}
# configure_miner ${MINER_IP} ${MINER_PORT} ${LOTUS_MINER_PATH}
# start_miner ${LOG_DIR}
# #stop_miner
# #start_miner ${LOG_DIR}
# wait_for_miner ${LOG_DIR}

- name: Create parameter cache directory
  file:
    path: "{{ param_cache }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0755'

- name: Create parent cache directory
  file:
    path: "{{ parent_cache }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0755'

- name: List existing wallets
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet list"
  register: wallet_list
  become_user: "{{ lotus_user }}"
  become: true
  changed_when: false

- name: If the wallet list is empty, set number_of_wallets to zero
  set_fact:
    number_of_wallets: 0
  when: wallet_list.stdout == ""

- name: If the wallet list is not empty, set number_of_wallets to the number of wallets in the list
  set_fact:
    number_of_wallets: "{{ wallet_list.stdout_lines[1:] | select('search', 'FIL') | list | length }}"
  when: wallet_list.stdout != ""

- name: If the owner wallet does not exist yet, create it.
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet new bls"
  register: create_wallet
  become_user: "{{ lotus_user }}"
  become: true
  when: number_of_wallets == 0

- name: If the worker wallet does not exist yet, create it.
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet new bls"
  register: create_wallet
  become_user: "{{ lotus_user }}"
  become: true
  # This when conditional is a little silly, but it should work consistently. We always want to create this second wallet if we create the first one.
  when: number_of_wallets == 1 or number_of_wallets == 0

- name: If both wallets exist already, set the addresses for the owner and worker wallets
  set_fact:
    owner_wallet_address: "{{ wallet_list.stdout_lines[1].split(' ')[0] }}"
    worker_wallet_address: "{{ wallet_list.stdout_lines[2].split(' ')[0] }}"
  when: number_of_wallets | int >= 2

- name: Print owner and worker wallet addresses
  debug:
    msg:
      - "Owner wallet address: {{ owner_wallet_address }}"
      - "Worker wallet address: {{ worker_wallet_address }}"
  when: owner_wallet_address is defined and worker_wallet_address is defined

- name: Prompt the user to transfer funds
  include_tasks: 09a-transfer_funds.yml