---
# tasks file for lotus_daemon
- name: Install prerequisites
  include_tasks: 01-install_prerequisites.yml

- name: Set limits and sysctl settings
  include_tasks: 02-set_limits_and_sysctl.yml

- name: Create log folder
  ansible.builtin.file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: 0700

- name: Build and install Lotus
  include_tasks: 03-build_and_install_lotus.yml

- name: Download chain snapshots
  include_tasks: 04-import_chain_snapshot.yml