---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: lotus_stable
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
  - name: lotus_oldstable
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
provisioner:
  name: ansible
verifier:
  name: ansible
