---
- name: Check out Lotus
  ansible.builtin.git:
    repo: "{{ lotus_git_repo }}"
    dest: "{{ build_dir }}/lotus"
    version: "{{ lotus_version }}"
    accept_newhostkey: true
    recursive: true
  become: false

- name: Execute lscpu to get CPU flags
  command:
    cmd: lscpu
  register: lscpu_output
  changed_when: False

- name: Extract flags from lscpu output
  set_fact:
    cpu_flags: "{{ lscpu_output.stdout_lines | join(' ') | regex_findall('\\b\\w+\\b') }}"

- name: Check if SHA_NI or SHA256 exist in CPU flags
  set_fact:
    has_sha256: "{{ 'sha256' in cpu_flags }}"
    has_sha_ni: "{{ 'sha_ni' in cpu_flags }}"

- name: Set build flags if SHA256 extensions were found
  set_fact:
    build_flags: "export RUSTFLAGS="-C target-cpu=native -g ; export FFI_BUILD_FROM_SOURCE=1 ; export FFI_USE_MULTICORE_SDR=0"
  when:
    - has_sha256
    - has_sha_ni

- name: Set build flags if SHA256 extensions were not found
  set_fact:
    build_flags: "export FFI_USE_MULTICORE_SDR=0"
  when:
    - not has_sha256
    - not has_sha_ni