---
- name: Deploy Lotus
  hosts: lotus_primary
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Ensure all packages are up to date
      ansible.builtin.apt:
        upgrade: dist

    - name: Create Lotus system group
      ansible.builtin.group:
        name: "{{ lotus_group }}"
        system: true
        state: present

    - name: Create Lotus system user
      ansible.builtin.user:
        name: "{{ lotus_user }}"
        comment: "Lotus Daemon User"
        shell: /bin/bash
        system: true
        createhome: true
        group: "{{ lotus_group }}"
        groups: "sudo,adm"
        append: true

  roles:
    - zorlin.lotus_daemon
    #- zorlin.lotus_miner
    #- zorlin.fil_boost
